#!/bin/bash

while read line
do
   #echo -e "$line\n"
   cp modeloESO ESO/"$line.md"
   sed -i "1s/.*/###${line}/" ESO/"$line.md"
done < materiasESO


while read line
do
   #echo -e "$line\n"
   cp modeloBachillerato Bachillerato/"$line.md"
   sed -i "1s/.*/###${line}/" Bachillerato/"$line.md"
done < materiasBachillerato
